[package]
name = "mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
azalea = { git = "https://github.com/azalea-rs/azalea", version = "0.13.0" }
tokio = { version = "1.37", features = ["full"] }
async-trait = "0.1"
parking_lot = "0.12.4"
anyhow = "1.0.99"
