pub const DISCORD_URL: &str = "https://lestallum.shinyshoe.net/discord";

#[derive(Clone, Copy)]
pub struct AreaInfo {
    pub slug: &'static str,
    pub name: &'static str,
    pub theme: &'static str,
    pub image: &'static str,
    pub warp_cmd: &'static str,
    pub accent_bar: &'static str,
    pub accent_text: &'static str,
    pub accent_rgb: &'static str,
    pub description: &'static str,
    pub long_description: &'static str,
    pub screenshots: &'static [&'static str],
}

pub const AREAS: &[AreaInfo] = &[
    AreaInfo {
        slug: "arboria",
        name: "Arboria",
        theme: "Gothic",
        image: "/img/areas/arboria/preview.webp",
        warp_cmd: "/t outpost Arboria",
        accent_bar: "bg-sky-500",
        accent_text: "text-sky-300",
        accent_rgb: "14,165,233",
        description: "An medieval gothic city near a lush spruce forest and a sunflower field.",
        long_description: "Arboria is a medieval gothic town perched above a rocky outcropping, crowned by a towering church and a walled city that overlooks the land below. Below the rock area, residents have built a quieter life surrounded by lush nature, rolling farmlands, and golden sunflower fields. The town traces its roots to Blackstone, an old settlement founded by HobbitTyrone that eventually fell into ruin, later claimed and revived by Lestallum, who preserved its gothic soul while expanding the settlement well beyond the old city walls.",
        screenshots: &["/img/areas/arboria/2024-01-09_07.22.24.webp","/img/areas/arboria/2024-01-09_07.39.31.webp","/img/areas/arboria/2024-01-09_07.53.03.webp","/img/areas/arboria/fb2024-01-09_08.00.05.webp","/img/areas/arboria/fb2024-06-01_02.54.42.webp","/img/areas/arboria/fb2024-08-21_12.50.21.webp","/img/areas/arboria/fb2024-08-21_12.53.30.webp","/img/areas/arboria/fb2024-08-21_12.56.22.webp","/img/areas/arboria/fb2024-08-21_13.01.19.webp","/img/areas/arboria/fb2024-08-21_13.04.56.webp","/img/areas/arboria/fb2024-11-21_13.48.26.webp","/img/areas/arboria/fb2024-11-21_13.54.36.webp","/img/areas/arboria/fb2025-05-08_06.20.33.webp","/img/areas/arboria/fb2025-05-08_06.23.03.webp","/img/areas/arboria/fb2025-05-08_06.44.20.webp","/img/areas/arboria/preview.webp"],
    },
    AreaInfo {
        slug: "evergreen-garden",
        name: "Evergreen Garden",
        theme: "Medieval",
        image: "/img/areas/evergreen_garden/preview.webp",
        warp_cmd: "/t outpost Evergreen",
        accent_bar: "bg-emerald-500",
        accent_text: "text-emerald-300",
        accent_rgb: "16,185,129",
        description: "A grid layout town area with a semi-strict medieval town theme.",
        long_description: "Evergreen Garden is a charming medieval town where organic, free-form plot. wHILE medieval aesthetic is encouraged, it is not strictly required, Residents are welcomed regardless of their building style here. Evergreen Gardens was originally founded as Port_Town by ThatsLewys in 2020, the town fell into ruins before Lestallum stepped in to revamp it entirely but still preserving a few point of intrests, including the iconic spawn tower that still stands today.",
        screenshots: &["/img/areas/evergreen_garden/fb2024-04-04_10.22.31.webp","/img/areas/evergreen_garden/preview.webp"],
    },
    AreaInfo {
        slug: "tsunamicity",
        name: "TsunamiCity",
        theme: "Futuristic",
        image: "/img/areas/tsunami_city/preview.webp",
        warp_cmd: "/t outpost Tsunami",
        accent_bar: "bg-cyan-500",
        accent_text: "text-cyan-300",
        accent_rgb: "6,182,212",
        description: "A gleaming semi-futuristic grid layout cityscape with neon-lit roads and a flying wyvern.",
        long_description: "TsunamiCity is a coastal futuristic city defined by its sleek grid layout, neon-lit streets, and the iconic wyvern that soars endlessly through the skies above(not moving too). The city holds deep historical significance as the predecessor to Lestallum itself. TsunamiCity(Town) was founded by TsunamiJackob in 2020, McShinyShoe took over as mayor in mid-2021, only for the city to later fall and be reborn as TsunamiCity_Neo under Ereyto's leadership with a futuristic overhaul. After a second collapse, Lestallum reclaimed the city and has been steadily rebuilding and expanding it ever since.",
        screenshots: &["/img/areas/tsunami_city/preview.webp"],
    },
    AreaInfo {
        slug: "tropicana",
        name: "Tropicana",
        theme: "Tropical",
        image: "/img/areas/tropicana/preview.webp",
        warp_cmd: "/t outpost Tropicana",
        accent_bar: "bg-amber-400",
        accent_text: "text-amber-300",
        accent_rgb: "251,191,36",
        description: "A vibrant tropical haven where palm trees sway and tropical builds dot the sun-drenched city.",
        long_description: "Tropicana is a laid-back coastal district lined with swaying palm trees along every road, giving it a breezy, tropical atmosphere. Though a tropical theme is encouraged, residents are free to build as they please. Once an outpost of TsunamiCity designed to house overflow players, the district was left unclaimed after the town's fall, until Lestallum swept in and gave it a new life.",
        screenshots: &["/img/areas/tropicana/fb2025-01-09_15.15.00.webp","/img/areas/tropicana/fb2025-01-09_15.15.52.webp","/img/areas/tropicana/fb2025-01-09_15.16.15.webp","/img/areas/tropicana/fb2025-01-09_15.16.32.webp","/img/areas/tropicana/fb2025-01-09_15.17.57.webp","/img/areas/tropicana/fb2025-01-09_15.22.25.webp","/img/areas/tropicana/fb2025-05-08_07.23.00.webp","/img/areas/tropicana/fb2025-05-08_07.23.26.webp","/img/areas/tropicana/fb2025-05-08_07.26.27.webp","/img/areas/tropicana/preview.webp"],
    },
    AreaInfo {
        slug: "leville",
        name: "Leville",
        theme: "Contemporary",
        image: "/img/areas/leville/preview.webp",
        warp_cmd: "/t outpost Leville",
        accent_bar: "bg-violet-500",
        accent_text: "text-violet-300",
        accent_rgb: "139,92,246",
        description: "A districted contemporary themed city that lies in the coastline that are divided by a canal.",
        long_description: "Leville holds a special place in Lestallum's history as its very first town area. It was once the heart of a small settlement called Shinsekai, a name meaning 'new world' and 'shin's world'. Though it has since been eclipsed in size by other town areas, Leville still used as the industrial and logistical backbone of Lestallum, housing the central storage network that serves the builders of the server. Visitors can access a range of public player warps here, including `/pw storage`, `/pw market`, `/pw farm`, `/pw cavern`, and `/pw pylon`.",
        screenshots: &["/img/areas/leville/2024-01-05_19.00.41.webp","/img/areas/leville/2024-01-05_19.15.29_3.webp","/img/areas/leville/fb2024-08-22_01.36.40.webp","/img/areas/leville/fb2025-05-02_00.47.38.webp","/img/areas/leville/fb2025-05-02_00.51.12.webp","/img/areas/leville/fb2025-05-02_00.54.00.webp","/img/areas/leville/fb2025-05-02_00.56.21.webp","/img/areas/leville/preview.webp"],
    },
    AreaInfo {
        slug: "clintwood",
        name: "Clintwood",
        theme: "Rustic",
        image: "/img/areas/clintwood/preview.webp",
        warp_cmd: "/t outpost Clintwood",
        accent_bar: "bg-rose-500",
        accent_text: "text-rose-300",
        accent_rgb: "244,63,94",
        description: "A rustic, down-to-earth neighborhood with a cozy frontier spirit and hand-crafted charm.",
        long_description: "Clintwood is a rustic, nature-integrated district with a loosely organic layout that feels more like a cozy settlement than a planned town. Little is known about who originally founded this land, but Lestallum eventually claimed it and has since shaped it into the cozy town area it is today.",
        screenshots: &["/img/areas/clintwood/preview.webp"],
    },
    AreaInfo {
        slug: "ofc",
        name: "OFC",
        theme: "Neoclassical",
        image: "/img/areas/ofc/preview.webp",
        warp_cmd: "/t outpost OFC",
        accent_bar: "bg-purple-700",
        accent_text: "text-purple-300",
        accent_rgb: "126,34,206",
        description: "A districted neoclassical themed town with a huge marketplace at the center of it, reserved for the high class society.",
        long_description: "OFC is a stately neoclassical district defined by grand architecture and a clear social hierarchy baked into its layout. There is a thriving marketplace anchors the center, flanked by the grand estates of the high class cavern elites, with residential neighborhoods filling the outer ring. The town carries a storied past as an independent nation and town called OFC. Its last owner a close friend of McShinyShoe before falling to inactivity. After changing hands several times through the server's former owner friend , the town was ultimately absorbed into Lestallum, which now stewards its legacy.",
        screenshots: &["/img/areas/ofc/preview.webp"],
    },
    AreaInfo {
        slug: "hive",
        name: "Hive",
        theme: "Enchanted",
        image: "/img/areas/hive/preview.webp",
        warp_cmd: "/t outpost Hive",
        accent_bar: "bg-yellow-500",
        accent_text: "text-yellow-300",
        accent_rgb: "234,179,8",
        description: "A medieval enchanted town buzzing with life, built around a sakura tree with bees flying around the town.",
        long_description: "Hive is a one-of-a-kind enchanted town that fuses medieval nature aesthetics with a bee and hive theme. At its heart stands a breathtaking sakura tree canopy, which once bore the record for the largest tree ever built on the server, which was crafted by CatitudeCutie. Originally known as The_Hive under the stewardship of FarmBee, the town passed to second-in-command Pirate after FarmBee unable to play, but the upkeep proved too great for pirate, leading Lestallum to merge the town into its fold to help preserving their land, with Pirate remaining as its dedicated area manager.",
        screenshots: &["/img/areas/hive/fb2025-02-02_15.17.48.webp","/img/areas/hive/fb2025-02-02_15.25.53.webp","/img/areas/hive/fb2025-02-02_15.38.25.webp","/img/areas/hive/fb2025-02-02_15.38.37.webp","/img/areas/hive/fb2025-02-02_15.38.49.webp","/img/areas/hive/fb2025-02-02_15.39.01.webp","/img/areas/hive/fb2025-02-02_15.39.17.webp","/img/areas/hive/fb2025-02-02_15.41.36.webp","/img/areas/hive/fb2025-02-02_15.48.12.webp","/img/areas/hive/fb2025-02-02_15.51.53.webp","/img/areas/hive/fb2025-02-02_15.54.11.webp","/img/areas/hive/fb2025-02-02_15.54.52.webp","/img/areas/hive/fb2025-02-02_15.56.30.webp","/img/areas/hive/fb2025-02-02_15.56.37.webp","/img/areas/hive/fb2025-02-02_15.57.20.webp","/img/areas/hive/fb2025-02-02_15.59.23.webp","/img/areas/hive/fb2025-02-02_15.59.44.webp","/img/areas/hive/fb2025-02-02_16.00.04.webp","/img/areas/hive/fb2025-02-02_16.01.12.webp","/img/areas/hive/fb2025-02-02_16.01.14.webp","/img/areas/hive/fb2025-02-02_16.01.30.webp","/img/areas/hive/fb2025-02-02_16.01.45.webp","/img/areas/hive/fb2025-02-02_16.02.43.webp","/img/areas/hive/fb2025-02-02_16.02.57.webp","/img/areas/hive/fb2025-02-02_16.04.31.webp","/img/areas/hive/preview.webp"],
    },
    AreaInfo {
        slug: "oasis",
        name: "Oasis",
        theme: "Desert",
        image: "/img/areas/oasis/preview.webp",
        warp_cmd: "/t outpost Oasis",
        accent_bar: "bg-teal-500",
        accent_text: "text-teal-300",
        accent_rgb: "20,184,166",
        description: "A serene hidden desert oasis with sandstone carved town built around the river, its carved build provides plentiful shading so that life can thrive within it.",
        long_description: "Oasis is a serene desert sanctuary nestled along a river, where homes and structures have been lovingly carved directly into sandstone hillsides, offering natural shade and shelter from the scorching desert surroundings. Despite the barren wastes that encircle it, life flourishes within the oasis, sustained by water, greenery, and a deep cultural heritage tied to the worship of Talon, an ancient griffin deity now long extinct. A ruined tomb dedicated to Talon lies west of the city, though it has since been overrun by bandits. When Lestallum reclaimed the oasis, there were only a handful of builds made, but the district has since grown dramatically, with a towering mountain and sweeping new builds transforming it into a quite vibrant landmark.",
        screenshots: &["/img/areas/oasis/fb2024-01-09_08.20.12.webp","/img/areas/oasis/preview.webp"],
    },
];
